### ISSUE TITLE
Small cardinalities make everything nominal/ordinal

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite-ui#103]
For example for this dataset

```csv
a,b,c
1.3,2,3
4.4,5,6
```

We interpret a, b, and c as ordinal values instead of quantitative values. 

The options we have are

* leave things as they are
* interpret floats as Q and ints as O
* interpret numbers as O only if there are fewer than 5% different values

I vote for the last option.

**Comment by kanitw** [comment]
The description is ambiguous -- please clarify.

**Comment by domoritz** [comment]
@kanitw thoughts?

**Comment by kanitw** [comment]
I do not understand what you mean by 

>  if there are fewer than 5% different values

Alternatively, we could also set all numeric values to Q by default and add a popup to ask if they want to pick suspicious field as ordinal

**Comment by kanitw** [comment]
@domoritz can you clarify my question?

**Comment by domoritz** [comment]
> interpret numbers as O only if there are fewer than 5% different values

My previous self meant that if there is less than 1 unique value per 20 tuples, then we should interpret things as ordinal. Otherwise quantitative. But I'm not sure how well this heuristic works.

**Comment by kanitw** [comment]
Ok I think we'll go with your last proposal

**Comment by kanitw** [comment]
This will be fixed as a part of https://github.com/uwdata/compassql/issues/88 and #182
