### ISSUE TITLE
Make #data-select just a text rather than a select box and move example dataset to be a tab in the pop-up

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite-ui#113]
Make `#data-select` just a div rather than `<select>` and move example dataset list to be a tab in the pop-up.

**Comment by kadamwhite** [comment]
The last piece of this is a final PR for the button in the sidebar

**Comment by kadamwhite** [comment]
The last piece of this is in PR at vega/voyager#212: I am closing this issue
