### ISSUE TITLE
Consider explicitly opting-in to angular animations

### ISSUE THREAD

**Issue by kadamwhite** [vega/vega-lite-ui#132]
This article from today's Angular Weekly newsletter proposed an interesting optimization around configuring Angular to explicitly skip animation handling for elements without a certain classname:

http://www.bennadel.com/blog/2935-enable-animations-explicitly-for-a-performance-boost-in-angularjs.htm

Since (to my knowledge) the Vega projects do not make heavy (or possibly any) use of `ngAnimate` animations, this could be a nice way to remove unneeded processing from Angular's draw loop.

**Comment by domoritz** [comment]
If we don't use ng animate, don't we already have an optimized version?

**Comment by kadamwhite** [comment]
You make a good point! I had misapprehended that it was a part of Angular core, but it looks like you are correct and that it is a separate module. *nevermind* :)
