### ISSUE TITLE
need 0.8.0 tag

### ISSUE THREAD

**Issue by rjmorris** [vega/vega-lite-ui#139]
I'm trying to install polestar, but when I run `npm install` I eventually get an error from bower:

    bower ENORESTARGET  No tag found that was able to satisfy ^0.8.0

    Additional error details:
    Available versions in git://github.com/uwdata/vega-lite-ui.git: 0.7.18, 0.7.17, 0.7.16, 0.7.14, 0.7.13, 0.7.12, 0.7.10, 0.7.9, 0.7.8, 0.7.6, 0.7.5, 0.7.4, 0.7.3, 0.7.2, 0.7.1, 0.7.0, 0.6.3, 0.6.2, 0.6.1, 0.6.0

Looking at vega-lite-ui's GitHub page, I see that the version in package.json is 0.8.0, but the latest tag is 0.7.18. I'm a novice with npm and bower, so maybe I'm wrong, but it looks like vega-lite-ui's version was bumped to 0.8.0 but no corresponding tag was created.

**Comment by rjmorris** [comment]
The 0.8.0 tag was added soon after I opened this issue, so I'm closing it.

**Comment by kanitw** [comment]
Apologies. I forgot to publish the latest version.
Thank you for reporting!
