### ISSUE TITLE
Scrollbars are always hidden

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite-ui#143]
The visualization views never show scrollbars. While this may be okay if you have a touchpad, it is not okay for people with mice since they often don't support horizontal scrolling well. 

We should use `overflow: auto` instead of `overflow: hidden`. 

Not sure exactly where we have to fix this but I have seen this issue in the bookmark gallery.

**Comment by kanitw** [comment]
horizontal?

**Comment by domoritz** [comment]
Prefer this
![screen shot 2015-10-23 at 14 08 04](https://cloud.githubusercontent.com/assets/589034/10705004/8c1bdb6e-798f-11e5-99e3-162421563d04.png)

Over this
![screen shot 2015-10-23 at 14 08 14](https://cloud.githubusercontent.com/assets/589034/10704995/86dede9e-798f-11e5-847d-5165a9998d15.png)

**Comment by kanitw** [comment]
I don't think the issue is overflow:hidden, otherwise you can't even scroll.

**Comment by domoritz** [comment]
Even better: only show the scrollbars like we do in the main gallery but also do this in the bookmark gallery.

**Comment by kanitw** [comment]
Not an issue anymore
