### ISSUE TITLE
Modal close events are not triggered correctly

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite-ui#151]
I see BOOKMARK_OPEN events when I launch the app but not when I actually open the dialog. Also, I doubt that we log events on escape.

**Comment by kanitw** [comment]
Partly fixed in https://github.com/vega/polestar/commit/568e4e484dc3817fad3dcc0e8e14285be82d0d1b

**Comment by kanitw** [comment]
and in https://github.com/vega/vega-lite-ui/pull/233/commits/30a9860597a4a38b3e0906289e38fe3e709b40a3
