### ISSUE TITLE
Discussion: should we compile vega-lite-ui?

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite-ui#17]
@domoritz 

Right now we compile `vega-lite-ui` into `vlui.js` and import to Polestar and Voyager via `wiredep` package which include the `main` file in `bower.json`.  

However, this makes it harder to track back to original source file when debugging as it will point to line numbers in vlui.js.     Should we remove `vlui.js` from `bower.json`’s `main` and manually include `bower_components/vega-lite-ui/src/**/*.{js/html/scss}` in Polestar and Voyager’s `gulp/inject.js`?

**Comment by domoritz** [comment]
Agree. It's painful to have multiple gulps running. Especially when a gulp task is failing in a terminal you are not looking at.

**Comment by kadamwhite** [comment]
I'm not familiar with gulp/inject.js; I'd be curious to know more about how that process works. I do see the difficulty with running multiple gulp processes but I'm slightly wary about nesting build processes.

Would including a source map with vlui.js partially resolve the debugging issue?

**Comment by kanitw** [comment]
It's possible to use source map so this isn't as painful as it was.
