### ISSUE TITLE
Quick Filter UI

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite-ui#177]

**Comment by kanitw** [comment]
We will need a slider UI for Q-filter. 

A few alternatives:  
- http://danielcrisp.github.io/angular-rangeslider/
- http://angular-slider.github.io/angularjs-slider/

There are some more available ...

**Comment by domoritz** [comment]
In an ideal world you could brush over a histogram ;-)

**Comment by kanitw** [comment]
Now we have a branch that works except for T, need to clean up in #204
