### ISSUE TITLE
More compact function select

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite-ui#196]
- [x] Basic – Instead of showing too many functions, show useful ones on top first.  

![hybridui_sketch](https://cloud.githubusercontent.com/assets/111269/16703542/6fb91454-4523-11e6-92a5-6141937afe99.png)

----

- [ ] VY2 – Support checkbox instead of radio and produce `values:[...]`

- [ ] Advance – Maybe group some of them into a select box

**Comment by ZeningQu** [comment]
If we want to do checkbox, is 

- [ ] NONE

really necessary?

`Select All` + `Clear` seem to be more commonly seen.

**Comment by kanitw** [comment]
For Polestar, it will remain radio. 

For Voyager2, if we allow enumerating functions.  `[x] None [x] Mean` means enumerate no aggregation and mean.  You can't do this without `None` checkbox.

**Comment by kanitw** [comment]
- [ ] in a follow up PR, try redesign timeunit function to be more usable.  (YEARMONTHDATEHOURMINUTE is absurd.  I guess users want to see "2015-01-15 18:00".

**Comment by ZeningQu** [comment]
For timeUnit function panel, what about this?
It's more compact. User can create any timeUnit, but they may also create timeUnit that doesn't make sense.

![timeunit functions](https://cloud.githubusercontent.com/assets/822034/16895533/7a29b8e2-4b2e-11e6-92a9-0515ff06d9f7.gif)

**Comment by kanitw** [comment]
You already have an answer why this is not a good idea :)

Look at Tableau for inspiration?
