### ISSUE TITLE
Clean-up Filter 

### ISSUE THREAD

**Issue by ZeningQu** [vega/vega-lite-ui#204]
- [x] Make toggle work
- [x] Q-Filter
  - [x] show filtered range (right now it only shows the raw data domain)
- [ ] T-Filter (waiting for https://github.com/vega/vega-lite/issues/1463)
  - [ ] T-Filter should call one of Q or C-Filter based on `timeUnit`
- [ ] You might want to rename `quantitiative-filter` module to `range-filter`
- [ ] You might want to rename `categorical-filter` module to `in-filter`

**Comment by kanitw** [comment]
@ZeningQu   Any progress on this issue, I don't see any updates regarding this at all.
