### ISSUE TITLE
Encoding + Filter can get too long

### ISSUE THREAD

**Issue by ZeningQu** [vega/vega-lite-ui#221]
![1](https://cloud.githubusercontent.com/assets/822034/17445093/1776319c-5af8-11e6-9536-48a60900036e.png)
![2](https://cloud.githubusercontent.com/assets/822034/17445099/1a08f17e-5af8-11e6-8cd3-c8e6b6547ed7.png)

**Comment by ZeningQu** [comment]
Data pane can get too long too.

![screen shot 2016-08-25 at 10 57 35 am](https://cloud.githubusercontent.com/assets/822034/17980141/c6c0867e-6ab2-11e6-96fb-dde52cd3391a.png)

**Comment by kanitw** [comment]
Moved to https://github.com/uwdata/voyager2/issues/180
