### ISSUE TITLE
timeUnit disappeared from function select

### ISSUE THREAD

**Issue by ZeningQu** [vega/vega-lite-ui#246]
Testing locally with `vega-lite-ui/master` and `voyager2/master`
timeUnit is not in function select 

![image](https://cloud.githubusercontent.com/assets/822034/17866266/bf8d8294-685a-11e6-9034-76b2b9945bb9.png)

**Comment by kanitw** [comment]
seems like we just forget to release compassql

**Comment by kanitw** [comment]
@ZeningQu Can you reproduce this? If not, please close.

**Comment by ZeningQu** [comment]
Close as timeUnits are now back!
