### ISSUE TITLE
Include raw domain min and max checkbox status not sync when field changes

### ISSUE THREAD

**Issue by ZeningQu** [vega/vega-lite-ui#281]
When user unchecks the "include raw domain min & max" checkbox and changes the x or y field and selects an aggregate function for the new field. The result chart will use the raw data domain but the checkbox will be unchecked

Observed in PoleStar during user study

**Comment by kanitw** [comment]
Can you remember a step to reproduce this?

**Comment by ZeningQu** [comment]
![oct-02-2016 21-46-11](https://cloud.githubusercontent.com/assets/822034/19027867/e79e0a4c-88e9-11e6-904f-1417e23a8a35.gif)

When you replace a field in shelf, `includeRawDomain` is true but the checkbox is not checked.
