### ISSUE TITLE
Bookmark view not syncing sort order

### ISSUE THREAD

**Issue by ZeningQu** [vega/vega-lite-ui#288]
If a chart is bookmarked, and then sorted differently in the main view, when user goes to the bookmark view, the sorting order will be out-of-sync.

Observed in Voyager-II user study

**Comment by kanitw** [comment]
Oh crap, the root cause is https://github.com/uwdata/compassql/issues/172

**Comment by kanitw** [comment]
This should not be a bug in the new rebuild.
