### ISSUE TITLE
Import Data from Google Sheet

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite-ui#30]
This is probably very useful as people can use google sheet for basic wrangling and also use google’s `IMPORTHTML` command to import web tables.

**Comment by domoritz** [comment]
Certainly useful! We should add another dataset importer for that but probably change the UI to use tabs. We got too many ways to import data at this point. I wish there was a service we could use that allows import from different sources.

**Comment by aranmohyeddin** [comment]
so is this possible?

**Comment by domoritz** [comment]
We don’t develop Vega lite ui anymore.
