### ISSUE TITLE
Automatically determine time unit 

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite-ui#47]
See discussion in https://github.com/vega/vega-lite-ui/pull/161

**Comment by domoritz** [comment]
Suggestion for rules

- if all the values spans multiple year -> then use `year`
- if all the values spans multiple months in one year -> then use `month`.   
- if all the values spans multiple days in one month -> then use `day`
- if all the values spans multiple hours in one day -> then use `hour-minute`

**Comment by kanitw** [comment]
This should be a part of CompassQL and maybe we import it for using with both polestar and navigator.

**Comment by kanitw** [comment]
Duplicate of #185
