### ISSUE TITLE
Highlight Selected Fields in Tooltip 

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite-ui#56]
Originally https://github.com/uwdata/polestar/issues/246

**Comment by kanitw** [comment]
@ZeningQu @domoritz  
For example, A B are selected in Voyager.  Then we consider a plot that contains A, B & C in Voyager.  
We might want to highlight A & B (or A, B &C).

**Comment by kanitw** [comment]
@ZeningQu Do we have support for this kind of thing in the tooltip plugin?

**Comment by ZeningQu** [comment]
@kanitw Currently there is no dynamic highlighting in the tooltip plugin.

**Comment by kanitw** [comment]
Moved to https://github.com/vega/vega-lite-ui/issues/56
