### ISSUE TITLE
Quick way for providing feedback

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite-ui#69]

**Comment by vlandham** [comment]
Currently, there is a 'report an issue' button - which links to a google form. The Form is using language that isn't really voyager specific - and perhaps with old names of some of the tools? 
And is pretty technical. We could use some of the same logic - but point to a form that is simpler and geared towards a more 'general audience'

<img width="713" alt="screen shot 2015-10-05 at 4 20 55 pm" src="https://cloud.githubusercontent.com/assets/9369/10292433/3bf2497c-6b7d-11e5-998b-a6c8b1bf9446.png">

**Comment by domoritz** [comment]
Create github issues instead?
