### ISSUE TITLE
Add dataset dialog is too wide for small screens.

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite-ui#72]
<img width="911" alt="screen shot 2015-09-23 at 09 40 06" src="https://cloud.githubusercontent.com/assets/589034/10051586/20e7ce22-61d7-11e5-9171-82f2dd7ac572.png">

The solution is to remove options from the Popup or use tabs. I think for now, we can hide the myria load.

**Comment by domoritz** [comment]
If you have this problem, zoom out, load your data, and then zoom back in.

**Comment by kadamwhite** [comment]
Taking this over to experiment with a solution

**Comment by domoritz** [comment]
Fixed for now. Permanent solution in #77
