### ISSUE TITLE
Provide a way to switch to different Myria instance

### ISSUE THREAD

**Issue by dundalek** [vega/vega-lite-ui#76]
At the moment the Myria instance is hardcoded for a demo and there is no way to change it from the UI. It would be nice if there was an input element so that I can specify my custom Myria instance.

**Comment by domoritz** [comment]
Addressed in #77

**Comment by domoritz** [comment]
@dundalek Most definitely. We are currently working on a complete overhaul of how people get data into polestar and voyager. Stay tuned. In the meantime, I disabled loading from myria because of an issue with the popup. Please let me know if you need that feature.

**Comment by dundalek** [comment]
Cool, new dataset loading sounds great. I can do without myria until it is ready.
