### ISSUE TITLE
Disable tracking in embedded mode

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite-ui#78]
Google analytics should not be used for embedded versions of polestar and voyager.

**Comment by vlandham** [comment]
whats the rational behind this? just that these would not be 'conical' uses of the tools - and thus shouldn't count towards other stats? 

It would be plausible to  split up stats by domain and thus still be able to distinguish stand alone apps from other uses.

**Comment by domoritz** [comment]
Discussed offline. We don't want to track the embedded instances.

**Comment by domoritz** [comment]
Related https://github.com/vega/vega-lite-ui/issues/84

**Comment by domoritz** [comment]
Done in polestar and voyager.
