### ISSUE TITLE
Minified library cannot be used

### ISSUE THREAD

**Issue by kadamwhite** [vega/vega-lite-ui#80]
See https://docs.angularjs.org/tutorial/step_05#a-note-on-minification -- We use the simple dependency syntax, e.g.
```js
angular.module('vlui')
  .directive('vlPlot', function(vl, vg, $timeout, $q, Dataset, Config, consts, _, $document, Logger, Heap) {
```
which is broken by the minification process because of how Angular looks up module names. We should explicitly specify dependency arrays, in the form of
```js
angular.module('vlui')
  .directive('vlPlot', [
    'vl', 'vg', '$timeout', '$q', 'Dataset', 'Config', 'consts', '_', '$document', 'Logger', 'Heap',
    function(vl, vg, $timeout, $q, Dataset, Config, consts, _, $document, Logger, Heap) {}
  ]);
```
or
```js
function directiveFn(vl, vg, $timeout, $q, Dataset, Config, consts, _, $document, Logger, Heap) {}
angular.module('vlui').directive('vlPlot', [
  'vl', 'vg', '$timeout', '$q', 'Dataset', 'Config', 'consts', '_', '$document', 'Logger', 'Heap'
, directiveFn]);
```
or similar.

Priority seems low for now, but doing this across our first-party dependencies will significantly affect how small we can make the bundled versions of Voyager & Polestar

**Comment by kadamwhite** [comment]
Looking at https://github.com/johnpapa/angular-styleguide#manually-identify-dependencies there may be a possibly-cleaner way to handle this: I've not used this before so it's hard to say how appropriate it would be, but adapting the code from the provided link would look like
```js
/* recommended */
function MyDirective($location, $routeParams, common, dataservice) {
  // ...
}

angular
  .module('app')
  .directive('MyDirective', MyDirective);

MyDirective.$inject = ['$location', '$routeParams', 'common', 'dataservice'];
```

**Comment by domoritz** [comment]
Isn't there a way to automatically do the correct inject by name? We should talk about this synchronously with @kanitw

**Comment by kadamwhite** [comment]
@domoritz The Angular guide recommends to use the `.$inject` option: https://docs.angularjs.org/guide/di#-inject-property-annotation I have not seen any solutions that maintain the implicit injection that don't break on minification.

This can definitely wait until @kanitw is back to discuss further

**Comment by kadamwhite** [comment]
Per our conversation today, I'm doing this for vega-lite-ui right now. However, I think I've changed my mind on using `$inject`: from the Angular docs, the array syntax is the "preferred" method, and the `$inject` approach would lead to unnecessarily expansive diffs:

Using "preferred" array syntax:
```diff
diff --git a/src/vlplotgroup/vlplotgroup.js b/src/vlplotgroup/vlplotgroup.js
index 3c3e296..9a44d33 100644
--- a/src/vlplotgroup/vlplotgroup.js
+++ b/src/vlplotgroup/vlplotgroup.js
@@ -6,8 +6,9 @@
  * @description
  * # visListItem
  */
-angular.module('vlui')
-  .directive('vlPlotGroup', function (Bookmarks, consts, vl, Dataset, Drop, Logger) {
+angular.module('vlui').directive('vlPlotGroup', [
+  'Bookmarks', 'consts', 'vl', 'Dataset', 'Drop', 'Logger',
+  function (Bookmarks, consts, vl, Dataset, Drop, Logger) {
     return {
       templateUrl: 'vlplotgroup/vlplotgroup.html',
       restrict: 'E',
@@ -139,4 +140,4 @@ angular.module('vlui')
         });
       }
     };
-  });
+  }]);
```

Using `$inject`:
```diff
diff --git a/src/vlplotgroup/vlplotgroup.js b/src/vlplotgroup/vlplotgroup.js
index 3c3e296..9907a6b 100644
--- a/src/vlplotgroup/vlplotgroup.js
+++ b/src/vlplotgroup/vlplotgroup.js
@@ -1,5 +1,141 @@
 'use strict';
 
+function vlPlotGroupDirective(Bookmarks, consts, vl, Dataset, Drop, Logger) {
+  return {
+    templateUrl: 'vlplotgroup/vlplotgroup.html',
+    restrict: 'E',
+    replace: true,
+
+    [ ~ 125 LINES ADDED ]
+
+  };
+}
+
+vlPlotGroupDirective.$inject = ['Bookmarks', 'consts', 'vl', 'Dataset', 'Drop', 'Logger'];
+
 /**
  * @ngdoc directive
  * @name vega-lite-ui.directive:visListItem
@@ -7,136 +143,4 @@
  * # visListItem
  */
 angular.module('vlui')
-  .directive('vlPlotGroup', function (Bookmarks, consts, vl, Dataset, Drop, Logger) {
-    return {
-      templateUrl: 'vlplotgroup/vlplotgroup.html',
-      restrict: 'E',
-      replace: true,
-
-      [ ~ 125 LINES REMOVED ]
-
-    };
-  });
+  .directive('vlPlotGroup', vlPlotGroupDirective);

```

I will proceed with the change using the array syntax demonstrated in the first diff.
