### ISSUE TITLE
Allow configuration of vlui from users

### ISSUE THREAD

**Issue by vlandham** [vega/vega-lite-ui#84]
This was brought up in adding Google analytics to vlui for voyager. How to customize various parameters based on what platform the library is being used on.

from KAdam: 

Given that vega-lite-ui is a library, not an application in and of itself, I'd expect there to be a configuration method for this rather than a config file itself—the configuration I'd assume to live in Voyager or Polestar, which would then pass it in to vlui as configuration.

This is the basic approach I've taken when I've extracted libraries out of larger applications, such as my mbtapi subway predictions client:

```
var mbtapi = require('mbtapi').create({
  apiKey: 'yourAPIkeyGoesHere'
});
```

(create was relevant in my app, `config()` or `analyticsConfig()` may be more appropriate in this case)

Some of the relevant configurations that should be dealt with in this manner:
- if logging is on or off (currently controlled in vlui `consts` object
- GA key 
- Mira config. 
- if mira import is on or off

**Comment by domoritz** [comment]
That sounds great and is actually related to what I was talking about today when I asked for a way to call internal API methods from outside the app. We could use the configuration to pass in callback function (for example callback on export) and set the embed configuration.

**Comment by vlandham** [comment]
I believe this usecase is handled in angular with a [provider](http://www.learn-angular.org/#!/lessons/the-provider-recipe). I will look to implement this vlui customization from its dependents using a provider.

**Comment by vlandham** [comment]
@domoritz Here is the email I sent KAdam a while ago around this issue. So far, I haven't gotten much further. Thoughts?

I pushed what I've been brainstorming on configuring vlui to a branch:
https://github.com/vega/vega-lite-ui/commit/e67492f3e18b6a6f7ec44145b6d2e94b37e461be

I was trying two different approaches - and i still don't know which one to pursue.

This one creates a new provider that returns a basic config object. The config object can be configured by the provider in Voyager's config function. Something like:

```
    vluiConfigProvider
      .setLogging(true);
```

The provider recipe in angular looks more like it should be used as a factory that allows for customization. So perhaps what I should be doing is creating a `logProvider` that returns a customized log service. But so far I haven't figured out how to get providers to return instances of services. Additionally, this would mean we would have providers for each of the things we wanted to customize - which seems like a lot more hassle. 

Compounding this - I haven't figured out how one provider can customize another provider during a config.... maybe its simple.... But for now, voyager would also be configuring 3rd party providers like the Analytics provider to set the GA key:

```
AnalyticsProvider
      .setAccount({ tracker: 'UA-44428446-4', name: 'voyager', trackEvent: true });
```

which seems redundant.

**Comment by domoritz** [comment]
I'm a bit lost here. Would we be able to set things on the provider before we initialize the app? Why don't we just have one endpoint for things we want to configure from the outside and the internally we wire things up?

**Comment by vlandham** [comment]
the provider, if i understand correctly, would be available in the `config` function of the parent - so voyager or polestar. Not sure if what you are suggesting is different from this approach - but I may be missing something.

**Comment by kadamwhite** [comment]
An alternative implementation could be to make a service `appConfig`, which has getters and setters for each property; so, any function that logs analytics could

```js
if ( appConfig.get( 'analyticsEnabled' ) ) {
  // ...
}
```
and then a consuming application could
```js
appConfig.set({
  analyticsEnabled: true,
  analyticsID: 'MY-GA-ID'
});
```
or
```js
appConfig.set( 'analyticsEnabled', false );
```

I don't know whether this would execute farther along in the app lifecycle than a provider; if so, the provider approach may be preferable.
