### ISSUE TITLE
Text overflow for long field names does not work

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite-ui#94]
If we have a long field name, it just wraps.

**Comment by kanitw** [comment]
Plus, it blocks remove button as reported in https://github.com/vega/polestar/issues/374

**Comment by kanitw** [comment]
Fixed in 	4fb0b58   if you find any related  problem, please reopen this.

**Comment by ZeningQu** [comment]
Reopen as I see this again with the latest vlui master and voyager2 master.

**Comment by ZeningQu** [comment]
I don't see this any more

**Comment by kanitw** [comment]
Broken Wildcard label https://github.com/uwdata/voyager2/issues/221 is probably an instance of this.
